"""
Train Enhanced Multi-Output ML Models
──────────────────────────────────────
Using the enhanced global pollution dataset with 60+ cities:
  1. Health Risk Level — Best / Healthy / Moderate / Unhealthy / Very Unhealthy / Hazardous
  2. Dominant Pollutant — which chemical is the primary cause
  3. AQI Category — EPA-standard classification

Also generates comprehensive city rankings with:
  • Per-pollutant breakdowns
  • AI-powered control recommendations
  • Category-wise city groupings
  • Pollutant hotspot analysis
"""
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import pickle, json, os

np.random.seed(42)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ─────────────────────────────────────────────
# 1. Load dataset (generated by generate_dataset.py)
# ─────────────────────────────────────────────
CSV_PATH = os.path.join(BASE_DIR, "city_health_aqi_dataset.csv")
print("📂 Loading dataset...")
df = pd.read_csv(CSV_PATH)
print(f"   {len(df):,} rows loaded")
print(f"   Cities: {df['City'].nunique()}")
print(f"   Continents: {df['Continent'].nunique()}")

# ── AI Control Recommendations Database ─────────────────────────────────────
CONTROL_RECOMMENDATIONS = {
    "PM2.5": {
        "source": "Vehicle exhausts, industrial emissions, crop burning, construction dust",
        "strategies": [
            "Deploy AI-optimized traffic management to reduce congestion hotspots",
            "Install smart air purification towers at high-density intersections",
            "Use satellite + ML to detect and prevent crop burning events in real-time",
            "Implement IoT dust suppression systems on construction sites",
            "AI-powered emission monitoring for industrial zones with auto-alerts",
            "Deploy predictive models to issue early warnings 48hrs before PM2.5 spikes",
        ],
        "tech": "Random Forest + LSTM forecasting, satellite imagery CNNs, IoT sensor networks",
    },
    "NO2": {
        "source": "Vehicle engines (diesel), power plants, industrial boilers",
        "strategies": [
            "AI traffic signal optimization to minimize idling and stop-go emissions",
            "ML-based fleet electrification planning for public transport routes",
            "Smart congestion pricing using real-time pollution sensors",
            "Predictive maintenance alerts for industrial emission control equipment",
            "AI route optimization for delivery vehicles to cut diesel NOx output",
            "Deploy neural network models to identify illegal emission vehicles",
        ],
        "tech": "Reinforcement learning for traffic, computer vision for enforcement, time-series forecasting",
    },
    "Ozone": {
        "source": "Secondary pollutant formed from NOx + VOCs under sunlight",
        "strategies": [
            "AI-based VOC emission tracking from industrial and commercial sources",
            "ML models to predict ozone formation windows and issue advisories",
            "Smart scheduling of industrial activities to avoid peak sunlight hours",
            "Deploy anomaly detection on VOC sensors for early leak identification",
            "AI urban planning tools to optimize green cover for ozone absorption",
            "Predictive models correlating weather + traffic + ozone for proactive response",
        ],
        "tech": "Chemical transport models + ML, anomaly detection, weather-coupled forecasting",
    },
    "CO": {
        "source": "Incomplete combustion — vehicles, generators, cooking stoves, wildfires",
        "strategies": [
            "AI-powered wildfire detection using satellite and drone imagery",
            "ML-optimized clean cooking stove distribution in underserved areas",
            "Smart grid management to reduce reliance on diesel generators",
            "Real-time CO hotspot mapping with IoT sensor fusion and edge AI",
            "Predictive models for generator usage spikes during power outages",
            "AI-based ventilation management for enclosed urban corridors",
        ],
        "tech": "YOLOv8 fire detection, IoT edge computing, smart grid optimization",
    },
    "PM10": {
        "source": "Road dust, construction, mining, agricultural activities, natural dust storms",
        "strategies": [
            "AI-controlled road sweeping schedules based on dust prediction models",
            "ML dust storm early warning using satellite and weather data fusion",
            "Smart sprinkler systems triggered by real-time PM10 sensor readings",
            "AI monitoring of mining and quarrying operations for compliance",
            "Drone-based dust mapping for construction site management",
            "Predictive models for agricultural dust events during harvest season",
        ],
        "tech": "Satellite dust tracking, drone surveying, IoT sprinkler automation",
    },
    "SO2": {
        "source": "Coal-burning power plants, oil refineries, smelting, volcanic activity",
        "strategies": [
            "AI optimization of flue gas desulfurization (FGD) systems",
            "ML-based coal quality prediction to minimize sulfur content selection",
            "Real-time refinery emission monitoring with AI anomaly detection",
            "Predictive maintenance for scrubber systems to prevent SO2 leaks",
            "AI energy mix optimization to phase out high-sulfur fuel sources",
            "Smart cap-and-trade systems using ML for emission credit pricing",
        ],
        "tech": "Process optimization AI, predictive maintenance, energy transition models",
    },
}

def aqi_to_category(aqi):
    if aqi <= 50:  return "Good"
    if aqi <= 100: return "Moderate"
    if aqi <= 150: return "Unhealthy for Sensitive Groups"
    if aqi <= 200: return "Unhealthy"
    if aqi <= 300: return "Very Unhealthy"
    return "Hazardous"

def aqi_to_health(aqi):
    if aqi <= 25:  return "Best"
    if aqi <= 50:  return "Healthy"
    if aqi <= 100: return "Moderate"
    if aqi <= 150: return "Unhealthy"
    if aqi <= 300: return "Very Unhealthy"
    return "Hazardous"

def aqi_to_quality(aqi):
    """Human-friendly 7-level quality label: Best → Worst."""
    if aqi <= 25:  return "Best"
    if aqi <= 50:  return "Better"
    if aqi <= 100: return "Good"
    if aqi <= 150: return "Moderate"
    if aqi <= 200: return "Bad"
    if aqi <= 300: return "Worse"
    return "Worst"

# ─────────────────────────────────────────────
# 2. Train Model 1: Health Risk Classifier
# ─────────────────────────────────────────────
FEATURES = ["CO AQI Value", "Ozone AQI Value", "NO2 AQI Value",
            "PM2.5 AQI Value", "PM10 AQI Value", "SO2 AQI Value"]

X = df[FEATURES].values

# Health risk model
le_health = LabelEncoder()
y_health = le_health.fit_transform(df["Health Risk"].values)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_health, test_size=0.2, random_state=42, stratify=y_health
)

print("\n🌲 Training Health Risk Classifier (Gradient Boosting)...")
health_model = GradientBoostingClassifier(
    n_estimators=250, max_depth=6, learning_rate=0.1, random_state=42
)
health_model.fit(X_train, y_train)
y_pred = health_model.predict(X_test)
health_acc = accuracy_score(y_test, y_pred)
print(f"✅ Health Risk Accuracy: {health_acc * 100:.2f}%")
print(classification_report(y_test, y_pred, target_names=le_health.classes_))

# ─────────────────────────────────────────────
# 3. Train Model 2: Dominant Pollutant Classifier
# ─────────────────────────────────────────────
le_pollutant = LabelEncoder()
y_pollutant = le_pollutant.fit_transform(df["Dominant Pollutant"].values)

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X, y_pollutant, test_size=0.2, random_state=42, stratify=y_pollutant
)

print("\n🧪 Training Dominant Pollutant Classifier (Random Forest)...")
pollutant_model = RandomForestClassifier(
    n_estimators=200, max_depth=None, random_state=42, n_jobs=-1
)
pollutant_model.fit(X_train2, y_train2)
y_pred2 = pollutant_model.predict(X_test2)
pollutant_acc = accuracy_score(y_test2, y_pred2)
print(f"✅ Dominant Pollutant Accuracy: {pollutant_acc * 100:.2f}%")
print(classification_report(y_test2, y_pred2, target_names=le_pollutant.classes_))

# ─────────────────────────────────────────────
# 4. Save model files
# ─────────────────────────────────────────────
with open(os.path.join(BASE_DIR, "health_model.pkl"), "wb") as f:
    pickle.dump(health_model, f)
with open(os.path.join(BASE_DIR, "health_label_encoder.pkl"), "wb") as f:
    pickle.dump(le_health, f)
with open(os.path.join(BASE_DIR, "pollutant_model.pkl"), "wb") as f:
    pickle.dump(pollutant_model, f)
with open(os.path.join(BASE_DIR, "pollutant_label_encoder.pkl"), "wb") as f:
    pickle.dump(le_pollutant, f)

# ─────────────────────────────────────────────
# 5. Build comprehensive city summary
# ─────────────────────────────────────────────
city_summary = []
for (city, country), g in df.groupby(["City", "Country"]):
    row = g.iloc[0]
    avg_aqi = int(g["AQI Value"].mean())

    # Per-pollutant averages
    pol_avgs = {
        "CO":    round(g["CO AQI Value"].mean(), 1),
        "Ozone": round(g["Ozone AQI Value"].mean(), 1),
        "NO2":   round(g["NO2 AQI Value"].mean(), 1),
        "PM2.5": round(g["PM2.5 AQI Value"].mean(), 1),
        "PM10":  round(g["PM10 AQI Value"].mean(), 1),
        "SO2":   round(g["SO2 AQI Value"].mean(), 1),
    }

    dominant = max(pol_avgs, key=pol_avgs.get)
    ctrl = CONTROL_RECOMMENDATIONS.get(dominant, CONTROL_RECOMMENDATIONS["PM2.5"])

    city_summary.append({
        "city": city,
        "country": country,
        "continent": row["Continent"],
        "latitude": float(row["Latitude"]) if "Latitude" in row.index else 0,
        "longitude": float(row["Longitude"]) if "Longitude" in row.index else 0,
        "population_millions": float(row["Population_Millions"]),
        "avg_aqi": avg_aqi,
        "aqi_category": aqi_to_category(avg_aqi),
        "aqi_quality": aqi_to_quality(avg_aqi),
        "health_risk": aqi_to_health(avg_aqi),
        "dominant_pollutant": dominant,
        "pollutant_averages": pol_avgs,
        "pollution_sources": ctrl["source"],
        "ai_control_strategies": ctrl["strategies"][:3],
        "ai_tech_stack": ctrl["tech"],
    })

city_summary.sort(key=lambda x: x["avg_aqi"])

# Category-wise grouping
category_groups = {}
for c in city_summary:
    cat = c["aqi_category"]
    if cat not in category_groups:
        category_groups[cat] = []
    category_groups[cat].append({
        "city": c["city"],
        "country": c["country"],
        "avg_aqi": c["avg_aqi"],
        "aqi_quality": c.get("aqi_quality", ""),
        "latitude": c.get("latitude", 0),
        "longitude": c.get("longitude", 0),
        "dominant_pollutant": c["dominant_pollutant"],
    })

# Quality-wise grouping
quality_groups = {}
for c in city_summary:
    q = c.get("aqi_quality", "")
    if q not in quality_groups:
        quality_groups[q] = []
    quality_groups[q].append({
        "city": c["city"],
        "country": c["country"],
        "avg_aqi": c["avg_aqi"],
        "latitude": c.get("latitude", 0),
        "longitude": c.get("longitude", 0),
        "dominant_pollutant": c["dominant_pollutant"],
    })

# Pollutant hotspots
pollutant_hotspots = {}
for pol in ["PM2.5", "NO2", "Ozone", "CO", "PM10", "SO2"]:
    hotspot_cities = sorted(city_summary, key=lambda x: x["pollutant_averages"][pol], reverse=True)[:10]
    ctrl = CONTROL_RECOMMENDATIONS[pol]
    pollutant_hotspots[pol] = {
        "top_cities": [{"city": c["city"], "country": c["country"],
                        "avg_value": c["pollutant_averages"][pol],
                        "latitude": c.get("latitude", 0),
                        "longitude": c.get("longitude", 0)} for c in hotspot_cities],
        "source": ctrl["source"],
        "ai_strategies": ctrl["strategies"],
        "tech_stack": ctrl["tech"],
    }

# ─────────────────────────────────────────────
# 6. Save comprehensive metadata
# ─────────────────────────────────────────────
meta = {
    "features": FEATURES,
    "health_classes": list(le_health.classes_),
    "pollutant_classes": list(le_pollutant.classes_),
    "health_accuracy": round(health_acc, 4),
    "pollutant_accuracy": round(pollutant_acc, 4),
    "dataset_rows": len(df),
    "cities": df["City"].nunique(),
    "continents": sorted(df["Continent"].unique().tolist()),
    "category_distribution": df["AQI Category"].value_counts().to_dict(),
    "quality_distribution": df["AQI Quality"].value_counts().to_dict() if "AQI Quality" in df.columns else {},
    "city_rankings": city_summary,
    "category_wise_cities": category_groups,
    "quality_wise_cities": quality_groups,
    "pollutant_hotspots": pollutant_hotspots,
    "ai_control_database": CONTROL_RECOMMENDATIONS,
}
with open(os.path.join(BASE_DIR, "health_model_meta.json"), "w") as f:
    json.dump(meta, f, indent=2, ensure_ascii=False)

print(f"\n📦 Saved:")
print(f"   health_model.pkl + health_label_encoder.pkl")
print(f"   pollutant_model.pkl + pollutant_label_encoder.pkl")
print(f"   health_model_meta.json (incl. {len(city_summary)} city rankings + AI control strategies)")
print(f"   city_health_aqi_dataset.csv ({len(df):,} rows)")

print(f"\n🏆 Top 5 CLEANEST Cities:")
for c in city_summary[:5]:
    print(f"   ✅ {c['city']}, {c['country']}: avg AQI {c['avg_aqi']} ({c['aqi_category']}) — dominated by {c['dominant_pollutant']}")

print(f"\n⚠️  Top 5 MOST POLLUTED Cities:")
for c in city_summary[-5:]:
    print(f"   🔴 {c['city']}, {c['country']}: avg AQI {c['avg_aqi']} ({c['aqi_category']}) — dominated by {c['dominant_pollutant']}")

print(f"\n🌍 Cities by Category:")
for cat in ["Good", "Moderate", "Unhealthy for Sensitive Groups", "Unhealthy", "Very Unhealthy", "Hazardous"]:
    cities = category_groups.get(cat, [])
    print(f"   {cat}: {len(cities)} cities")

print(f"\n🎉 Done! Enhanced models with AI control strategies ready for AURA.")
